#!/bin/bash

# list of functions
# check_root
# check_ptu_loaded
# check_vtune_loaded
# which_is_loaded
# unload_vtune
# unload_ptu
# load_vtune
# load_ptu

PTU_ROOT=/opt/intel/ptu40_003_lin_intel64/
VTUNE_ROOT=/opt/intel/vtune/
VTUNE_AMP_ROOT=/opt/intel/vtune_amplifier_xe_2011

function usage {
cat <<EOF
$(basename $0) script loads, switches and unloads vtune, vtune_amp and ptu environements.
An environment includes:
  - kernel modules
  - devices in /dev
  - init files in /etc/init.d

Usage: $(basename $0) [options]
  Options:
    -h: display this help
    -l [vtune|vtune_amp|ptu]: load vtune or ptu
                    if one is already loaded, it unloads it first
    -u [vtune|vtune_amp|ptu]: unload vtune, vtune_amp or ptu
    -d: display which environement is loaded
EOF
}

is_loaded_vtune=0
is_loaded_vtune_amp=0
is_loaded_ptu=0

function check_root {
  # Make sure only root can run our script
  if [[ $UID -ne 0 ]]; then
    echo "You must be part of ptu or vtune group" 1>&2
    exit 87
  fi
}

function check_vtune_amp_loaded {
  if [[ -a /dev/sep3_1 ]] || [[ $(lsmod | \grep -c "sep3_1 ") -ne 0 ]] || 
    [[ -a /dev/pax ]] || [[ $(lsmod | \grep -c pax) -ne 0 ]] || 
    [[ -a /etc/init.d/sep3_1 ]]; then

    if [[ -a /dev/sep3_1 ]] && [[ $(lsmod | \grep -c "sep3_1 ") -ne 0 ]] &&
      [[ -a /dev/pax ]] && [[ $(lsmod | \grep -c pax) -ne 0 ]] &&
      [[ -a /etc/init.d/sep3_1 ]]; then
      is_loaded_vtune_amp=1;
    else
      echo "Error: VTune amp none entirely unloaded" >&2
    fi
  else
    is_loaded_amp=0;
  fi
}

function check_ptu_loaded {
  if [[ -a /dev/sep3 ]] || [[ $(lsmod | \grep -c "sep3 ") -ne 0 ]] || 
    [[ -a /dev/pax ]] || [[ $(lsmod | \grep -c pax) -ne 0 ]] || 
    [[ -a /etc/init.d/sep3 ]]; then

    if [[ -a /dev/sep3 ]] && [[ $(lsmod | \grep -c "sep3 ") -ne 0 ]] &&
      [[ -a /dev/pax ]] && [[ $(lsmod | \grep -c pax) -ne 0 ]] &&
      [[ -a /etc/init.d/sep3 ]]; then
      is_loaded_ptu=1;
    else
      echo "Error: PTU none entirely unloaded" >&2
    fi
  else
    is_loaded_ptu=0;
  fi
}

function check_vtune_loaded {
  if [[ -a /dev/vtune_d ]] || [[ $(lsmod | \grep -c vtune) -ne 0 ]] ||
    [[ -a /etc/init.d/vtune ]]; then

    if [[ -a /dev/vtune_d ]] && [[ $(lsmod | \grep -c vtune) -ne 0 ]] &&
      [[ -a /etc/init.d/vtune ]]; then
      is_loaded_vtune=1;
    else
      echo "Error: VTune none entirely unloaded" >&2
    fi
  else
    is_loaded_vtune=0;
  fi
}

function which_is_loaded {
  check_ptu_loaded
  check_vtune_loaded
  check_vtune_amp_loaded
  if [[ is_loaded_vtune -eq 0 ]] && [[ is_loaded_vtune_amp -eq 0 ]] && [[ is_loaded_ptu -eq 0 ]]; then
    echo "none is loaded"
  elif [[ is_loaded_vtune -eq 1 ]] && [[ is_loaded_vtune_amp -eq 1 ]] ||  [[ is_loaded_vtune -eq 1 ]] && [[ is_loaded_ptu -eq 1 ]] ||  [[ is_loaded_vtune_amp -eq 1 ]] && [[ is_loaded_ptu -eq 1 ]]; then
    echo "Error: both vtune and ptu are loaded!" >&2
  elif [[ is_loaded_vtune -eq 1 ]]; then
    echo "vtune is loaded"
  elif [[ is_loaded_vtune_amp -eq 1 ]]; then
    echo "vtune is loaded"
  elif [[ is_loaded_ptu -eq 1 ]]; then
    echo "ptu is loaded"
  fi
}

function unload_vtune {
  check_root
  echo "Unloading VTune environment"
  cd $VTUNE_ROOT/vdk/
  ./install-boot-script --uninstall
  ./rmmod-vtune
}

function unload_vtune_amp {
  check_root
  echo "Unloading VTune Amp environment"
  cd $VTUNE_AMP_ROOT/sepdk/src/pax/
  ./boot-script -u
  ./rmmod-pax
  cd $VTUNE_AMP_ROOT/sepdk/src/
  ./boot-script -u
  ./rmmod-sep3
}

function unload_ptu {
  check_root
  echo "Unloading PTU environment"
  cd $PTU_ROOT/sepdk/src/pax/
  ./boot-script -u
  ./rmmod-pax
  cd $PTU_ROOT/sepdk/src/
  ./boot-script -u
  ./rmmod-sep3
}

function load_vtune {
  check_root
  check_ptu_loaded
  check_vtune_amp_loaded
  if [[ is_loaded_vtune_amp -eq 1 ]]; then
    unload_vtune_amp
  fi
  if [[ is_loaded_ptu -eq 1 ]]; then
    unload_ptu
  fi
  cd $VTUNE_ROOT/vdk/
  ./install-boot-script --install
  ./insmod-vtune vtune
}

function load_vtune_amp {
  check_root
  check_vtune_loaded
  check_ptu_loaded
  if [[ is_loaded_ptu -eq 1 ]]; then
    unload_ptu
  fi
  if [[ is_loaded_vtune -eq 1 ]]; then
    unload_vtune
  fi
  cd $VTUNE_AMP_ROOT/sepdk/src/pax
  ./boot-script -i -g ptu
  ./insmod-pax -g ptu
  cd $VTUNE_AMP_ROOT/sepdk/src/
  ./boot-script -i -g ptu
  ./insmod-sep3 -g ptu
}

function load_ptu {
  check_root
  check_vtune_loaded
  check_vtune_amp_loaded
  if [[ is_loaded_vtune_amp -eq 1 ]]; then
    unload_vtune_amp
  fi
  if [[ is_loaded_vtune -eq 1 ]]; then
    unload_vtune
  fi
  cd $PTU_ROOT/sepdk/src/pax
  ./boot-script -i -g ptu
  ./insmod-pax -g ptu
  cd $PTU_ROOT/sepdk/src/
  ./boot-script -i -g ptu
  ./insmod-sep3 -g ptu
}

while getopts ":hdl:u:" opt; do
  case $opt in
    h)
      usage
      exit 0
      ;;
    d)
      which_is_loaded
      exit 0
      ;;
    l)
      if [[ "$OPTARG" != "ptu" ]] && [[ "$OPTARG" != "vtune" ]] && [[ "$OPTARG" != "vtune_amp" ]]; then
        echo "Error: load parameter must be ptu or vtune" >&2
        exit 1
      fi
      load_$OPTARG
      exit 0
      ;;
    u)
      if [[ "$OPTARG" != "ptu" ]] && [[ "$OPTARG" != "vtune" ]] && [[ "$OPTARG" != "vtune_amp"  ]]; then
        echo "Error: unload parameter must be ptu or vtune" >&2
        exit 1
      fi
      unload_$OPTARG
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
    *)
      usage
      exit 0
      ;;
  esac
done

# case of no options
usage


